apiVersion: v2
name: ch-appliance-helmchart
version: "1.5.0-84"
description: Cloudhedge Appliance Helm chart
keywords:
  - cloudhedge
  - chart
  - kubernetes
home: https://cloudhedge.io
maintainers:
  - name: Cloudhedge Engineering team
    email: engg@cloudhedge.io
appVersion: 1.5.0
dependencies:
- name: ch-chart-template
  version: 1.5.0
  alias: webapp
- name: ch-chart-template
  version: 1.5.0
  alias: auth-gateway-service
- name: ch-chart-template
  version: 1.5.0
  alias: core-engine
- name: ch-chart-template
  version: 1.5.0
  alias: notification-service
- name: ch-chart-template
  version: 1.5.0
  alias: vault-service
- name: ch-chart-template
  version: 1.5.0
  alias: activity-service
- name: ch-chart-template
  version: 1.5.0
  alias: discover-service-linux
- name: ch-chart-template
  version: 1.5.0
  alias: discover-service-windows  
- name: ch-chart-template
  version: 1.5.0
  alias: report-service
- name: ch-chart-template
  version: 1.5.0
  alias: logging-agent
- name: ch-chart-template
  version: 1.5.0
  alias: transform-service-linux
- name: ch-chart-template
  version: 1.5.0
  alias: transform-service-windows
- name: ch-chart-template
  version: 1.5.0
  alias: logging-service
- name: ch-chart-template
  version: 1.5.0
  alias: cruize-service
- name: ch-chart-template
  version: 1.5.0
  alias: license-service
- name: ch-chart-template
  version: 1.5.0
  alias: ch-user-guide
# - name: ch-chart-template
#   version: 1.4.1
#   alias: discover-service-aix
