apiVersion: v1
kind: PersistentVolume
metadata:
  name: ch-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: your-nfs-server
    path: "your-path"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ch-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi