#should be overriden while deployment
# serviceAccount: ch-service
nameOverride: ""
fullnameOverride: ""
appHost: ""
elkHost: ""

db:
  dbUser: "<placeholder>"
  dbPassword: "<placeholder>"
  dbUrl: "<placeholder>"
  dbName: "<placeholder>"

# global:
#   pvcName: ""
#   jwtSecret: "<placeholder>"
#   encryptSecret: "<placeholder>"
#   webappExposeType: LoadBalancer
#   image:
#     registry: registry.connect.redhat.com/cloudhedge
#     tag: ch-rel-1.3.3
#     imagePullSecrets:
#     - name: dockerpullsecret
#     in case of docker hub, quey.io provide username and password
#     username: <placeholder>
#     password: <placeholder>

# webapp:
#   nameOverride: webapp
#   container:
#     ports:
#       - containerPort: 8443
#         name: https
#         targetPort: 8443
#     livenessProbe:
#       initialDelaySeconds: 10
#       httpGet:
#         path: /
#         port: 8443
#         scheme: HTTPS
#     readinessProbe:
#       initialDelaySeconds: 10
#       httpGet:
#         path: /
#         port: 8443
#         scheme: HTTPS
#   image:
#     repository: webapp
#     tag: ch-rel-1.3.3 #tag-to-replace-webapp
#   envRefs:
#     - type: secretRef
#       ref: ch-secret
#   service:
#     type: LoadBalancer
#     sessionAffinity: ClientIP
#     ports: 
#     - port: 443
#       targetPort: 8443
#       name: https