#should be overriden while deployment, Optional
nameOverride: ""
fullnameOverride: ""
appHost: ""
elkHost: ""

# DB credentials, required
db:
  dbUser: "<placeholder>" # DB username, required
  dbPassword: "<placeholder>" # DB password, required
  dbUrl: "<placeholder>" # DB URL with port, required
  dbName: "<placeholder>" # Database name, required
  # dbProto: "<placeholder>" # DB protocol, Optional, default mongodb

# Global params
global: 
#   pvcName: "" # Persistent volume claim name, make sure your PVC is available in a given namespace, Optional
#   jwtSecret: "theEncryptSuperSecretValue" # JWT secret, Optional, default theJWTSuperSecretValue
#   encryptSecret: theEncryptSuperSecretValue # Encrypt secret, Optional, default theEncryptSuperSecretValue
  webappExposeType: NodePort # webapp expose type, Optional, default LoadBalancer, allowed values are LoadBalancer, NodePort and ClusterIP
  webappProtocol: HTTPS # Webapp Protocol, optional, default HTTP, allowed values are HTTP and HTTPS

#   # Add labels to all the deployed resources, Optional
#   commonLabels: {}

#   # Add annotations to all the deployed resources, Optional
#   commonAnnotations: {}

#   # Image details, Optional
#   image:
#     registry: registry.connect.redhat.com/cloudhedge # container image registry, Optional, default registry.connect.redhat.com/cloudhedge 
#     tag: ch-rel-1.3.3 # container image tag, Optional, default ch-rel-1.3.3

#     # Image pull secrets, Optional
#     imagePullSecrets:
#     - name: dockerpullsecret
    
#     # in case of private container registry, give user name and password to authenticate to pull the images, Optional
#     username: <placeholder>
#     password: <placeholder>

clusterDomain: cluster.local

webapp:
  image:
    repository: webapp
    tag: ch-rel-1.5.2-2 

aws-lift-shift:
  image:
    repository: aws-lift-shift
    tag: ch-rel-1.5.2-1 

core-engine:
  image:
    repository: core-engine
    tag: ch-rel-1.5.2-2 

auth-gateway-service:
  image:
    repository: auth-gateway-service
    tag: ch-rel-1.5.2-9 

cloud-infra-service:
  image:
    repository: cloud-infra-service
    tag: ch-rel-1.5.2-1 

notification-service:
  image:
    repository: notification-service
    tag: ch-rel-1.5.2-1 

vault-service:
  image:
    repository: vault-service
    tag: ch-rel-1.5.2-1 

activity-service:
  image:
    repository: activity-service
    tag: ch-rel-1.5.2-1 

discover-service-linux:
  image:
    repository: discover-service-linux
    tag: ch-rel-1.5.2-5 

discover-service-aix:
  image:
    repository: discover-service-aix
    tag: ch-rel-1.5.2-1 

discover-service-windows:
  image:
    repository:  discover-service-windows
    tag: ch-rel-1.5.2-3 

transform-service-linux:
  image:
    repository: transform-service-linux
    tag: ch-rel-1.5.2-3 

transform-service-windows:
  image:
    repository: transform-service-windows
    tag: ch-rel-1.5.2-1 

report-service:
  image:
    repository: report-service
    tag: ch-rel-1.5.2-1 

cruize-service:
  image:
    repository: cruize-service
    tag: ch-rel-1.5.2-2 

ch-user-guide:
  image:
    repository: ch-user-guide
    tag: ch-rel-1.5.2-3 
