apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ch-chart-template.fullname" . }}
  labels:
    app: {{ include "ch-chart-template.name" . }}
    chart: {{ include "ch-chart-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ch-chart-template.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "ch-chart-template.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      {{- if .Values.global.image.username }}
        - name: {{ .Release.Name }}-image-pull-secret
      {{- else if .Values.global.image.imagePullSecrets }}
        {{- range .Values.global.image.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      volumes:
      {{- if .Values.global.pvcName }}
      - name: ch-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.global.pvcName }}
      {{- end }}
      {{- if eq .Chart.Name "webapp" }}
      - name: webapp-config
        configMap:
          name: {{ .Release.Name }}-webapp
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ printf "%s/%s:%s" (.Values.global.image.registry | default "registry.connect.redhat.com/cloudhedge") (.Values.image.repository | default .Chart.Name )  (.Values.image.tag | default ( .Values.global.image.tag | default "ch-rel-1.3.3" )) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-app-service-urls
            - secretRef:
                name: {{ .Release.Name }}-secret
            {{- if .Values.envRefs }}
            {{- range .Values.envRefs }}
            {{- if eq .type "configMapRef" }}
            - configMapRef:
                name: {{ .ref }}
            {{- else if eq .type "secretRef" }}
            - secretRef:
                name: {{ .ref }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- if .Values.envs }}
          env:
            {{- range .Values.envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
          ports:
          - name: http
            containerPort: {{ include "findContainerPort" ( dict "component" .Chart.Name ) }}
            protocol: TCP
          volumeMounts:
            {{- if eq .Chart.Name "webapp" }}
            - name: webapp-config
              mountPath: /etc/nginx/
            {{- end }}
            {{- if .Values.global.pvcName  }}
            - name: ch-pvc
              mountPath: /opt/cloudhedge/shared
            {{- end }}
          {{- if ne .Chart.Name "logging-agent" }}
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: {{ include "findContainerPort" ( dict "component" .Chart.Name ) }}
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: {{ include "findContainerPort" ( dict "component" .Chart.Name ) }}
              scheme: HTTP
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}