apiVersion: v1
kind: Service
metadata:
  name: {{ include "ch-chart-template.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ include "ch-chart-template.name" . }}
    chart: {{ include "ch-chart-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if eq .Chart.Name "webapp" }}
  type: {{ .Values.global.webappExposeType | default "ClusterIP"}}
  {{- else }}
  type: ClusterIP
  {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
  - port: 80
    targetPort: {{ include "findContainerPort" ( dict "component" .Chart.Name ) }}
    protocol: TCP
    name: http
  selector:
    app: {{ include "ch-chart-template.name" . }}
    release: {{ .Release.Name }}