apiVersion: v1
kind: Service
metadata:
  name: {{ include "ch-chart-template.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ include "ch-chart-template.name" . }}
    chart: {{ include "ch-chart-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ default "http" .targetPort }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ default "http" .name | quote }}
    {{- end }}
  selector:
    app: {{ include "ch-chart-template.name" . }}
    release: {{ .Release.Name }}