apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.db.dbUser | quote }}
  DB_PASSWORD: {{ .Values.db.dbPassword | quote }}
  DB_PROTO: {{ .Values.db.dbProto | default "mongo" | quote }}
  DB_URL_WITH_PORT: {{ .Values.db.dbUrl | quote }}
  DB_NAME: {{ .Values.db.dbName | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | default "theJWTSuperSecretValue" | quote }}
  ENCRYPT_SECRET: {{ .Values.global.encryptSecret | default "theEncryptSuperSecretValue" | quote }}
