{{- $global := .Values.global | default dict }}
{{- $db := .Values.db | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels: {{- include "standardlabels" . | nindent 4 }}
    {{- if $global.commonLabels }}
    {{- include "commonlabels" ( dict "value" $global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $global.commonAnnotations }}
  annotations: {{- include "commonlabels" ( dict "value" $global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DB_USER: {{ $db.dbUser | quote }}
  DB_PASSWORD: {{ $db.dbPassword | quote }}
  DB_PROTO: {{ $db.dbProto | default "mongodb" | quote }}
  DB_URL_WITH_PORT: {{ $db.dbUrl | quote }}
  DB_NAME: {{ $db.dbName | quote }}
  JWT_SECRET: {{ $global.jwtSecret | default "theJWTSuperSecretValue" | quote }}
  ENCRYPT_SECRET: {{ $global.encryptSecret | default "theEncryptSuperSecretValue" | quote }}