{{- $global := .Values.global | default dict }}

{{- if $global.image }}
{{- if $global.image.username }}      
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-pull-secret
  labels: {{- include "standardlabels" . | nindent 4 }}
    {{- if $global.commonLabels }}
    {{- include "commonlabels" ( dict "value" $global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $global.commonAnnotations }}
  annotations: {{- include "commonlabels" ( dict "value" $global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}