{{- if .Values.global.image.username }}      
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}